### ISSUE TITLE
 How did the extraction species in the paper use the MetaPhlAn2 command to extract the original file?

### ISSUE THREAD

**Issue by cypowerAI** [jaeyunsung/GMHI_2020#2]
How did the extraction species in the paper use the MetaPhlAn2 command to extract the original file?

Now I use the following command to extract the original file, why the output file does not find the corresponding species information.

metaphlan2.py SRR5279229.fastq --bowtie2out SRR5279229_bowtie2out_mpa2.txt --nproc 8 --tax_lev s --input_type fastq -o SRR5279229_output_mpa2.txt

**Comment by jaeyunsung** [comment]
This is more of a question on how to use Metaphlan2, and not on GMHI. For questions regarding Metaphlan2, I suggest using their forum: https://forum.biobakery.org/c/microbial-community-profiling/metaphlan/7

Your command syntax looks correct. Are you sure you're running MetaPhlAn2 from the same directory where your input .fastq file is available? Otherwise, you'll need to provide the path to the input file.

**Comment by jaeyunsung** [comment]
This is more of a question on how to use Metaphlan2, and not on GMHI. For questions regarding Metaphlan2, I suggest using their forum: https://forum.biobakery.org/c/microbial-community-profiling/metaphlan/7

Your command syntax looks correct. Are you sure you're running MetaPhlAn2 from the same directory where your input .fastq file is available? Otherwise, you'll need to provide the path to the input file.
